force-app/main/default/objects/ZipCodeResult__c/ZipCodeResult__c.object-meta.xml
<CustomObject>
    <label>Zip Code Result</label>
    <nameField>
        <displayFormat>ZIP-{0000}</displayFormat>
        <label>Zip Code Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zip Code Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZipCodeResult__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeResult__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeResult__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZipCodeResult__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZipCodeResult__c/fields/PlaceName__c.field-meta.xml
<CustomField>
    <fullName>PlaceName__c</fullName>
    <label>Place Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeResult__c/fields/PostCode__c.field-meta.xml
<CustomField>
    <fullName>PostCode__c</fullName>
    <label>Post Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeResult__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZipCodeResult__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>State Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZipCodeInputController.cls
/**
 * Controller for ZipCodeInputCmp LWC
 */
public with sharing class ZipCodeInputController {
  /**
   * @description storeAPIResponse Stores retrieved results from API into object
   * @param  targetData targetData Target data to store
   * @return            return boolean to express result of save
   */
  @AuraEnabled(cacheable=false)
  public static boolean storeAPIResponse(ZipCodeStoreRequest targetData) {
    try {
      if (targetData.countryCode != 'US') {
        ZipCodeResult__c newData = new ZipCodeResult__c(
          Country__c = targetData?.country,
          CountryCode__c = targetData?.countryCode,
          Latitude__c = targetData?.latitude,
          Longitude__c = targetData?.longitude,
          State__c = targetData?.state,
          StateCode__c = targetData?.stateCode,
          PostCode__c = targetData?.postCode,
          PlaceName__c = targetData?.placeName
        );
        insert newData;
        return true;
      } else {
        return false;
      }
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * Transformation class for frontend data
   */
  public class ZipCodeStoreRequest {
    @AuraEnabled
    public String countryCode { get; set; }

    @AuraEnabled
    public String country { get; set; }

    @AuraEnabled
    public Decimal latitude { get; set; }

    @AuraEnabled
    public Decimal longitude { get; set; }

    @AuraEnabled
    public String postCode { get; set; }

    @AuraEnabled
    public String stateCode { get; set; }

    @AuraEnabled
    public String state { get; set; }

    @AuraEnabled
    public String placeName { get; set; }
  }
}