force-app/main/default/objects/Account/fields/Risk__c.field-meta.xml
<CustomField>
    <fullName>Risk__c</fullName>
    <label>Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RiskValueChange__e/RiskValueChange__e.object-meta.xml
<CustomObject>
    <label>Risk Value Change</label>
    <pluralLabel>Risk Value Changes</pluralLabel>
</CustomObject>

force-app/main/default/objects/RiskValueChange__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RiskValueChange__e/fields/RiskValue__c.field-meta.xml
<CustomField>
    <fullName>RiskValue__c</fullName>
    <label>Risk Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHelper.cls
/**
 * Helper class for handler of Account trigger
 */
public with sharing class AccountTriggerHelper {
  /**
   * @description publishPlatformEventOnRiskChange publishes a platform event on 'High' Risk value
   * @param  newRecordsMap newRecordsMap incoming changed Account records
   * @param  oldRecordsMap oldRecordsMap previous changed Account records
   */
  public void publishPlatformEventOnRiskChange(Map<Id, Account> newRecordsMap, Map<Id, Account> oldRecordsMap) {
    List<RiskValueChange__e> publishedEvents = new List<RiskValueChange__e>();
    Account prevAccount;
    Account currentAccount;

    for (Id recordId : newRecordsMap.keySet()) {
      try {
        prevAccount = oldRecordsMap.get(recordId);
        currentAccount = newRecordsMap.get(recordId);

        if (prevAccount.Risk__c != currentAccount.Risk__c && currentAccount.Risk__c == 'High') {
          RiskValueChange__e targetEvent = (RiskValueChange__e) RiskValueChange__e.sObjectType.newSObject(null, true);
          targetEvent.AccountId__c = currentAccount.Id;
          targetEvent.RiskValue__c = currentAccount.Risk__c;
          publishedEvents.add(targetEvent);
        }
      } catch (Exception ex) {
        currentAccount.addError('There was a problem saving your data, please try again');
      }
    }

    if (publishedEvents.size() > 0) {
      List<Database.SaveResult> results = EventBus.publish(publishedEvents);

      for (Database.SaveResult sr : results) {
        if (sr.isSuccess()) {
          System.debug('Successfully published event.');
        } else {
          for (Database.Error err : sr.getErrors()) {
            System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
          }
        }
      }
    }
  }
}